# General
name: zoltanp's blog
description: "Various stuff which I considered worth publishing."
url: http://127.0.0.1:4000

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]

paginate: 5
permalink: /:year/:month/:title.html

# Social share and comments.
enable-social-module: false
disqus-id: zoltanp-github-io # yourusername
twitter: false # yourusername
github: zoltanp
google: false # +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
