# General
name: zoltanp's blog
description: "Various stuff which I considered worth publishing."
url: http://localhost:4000

markdown: kramdown
highlighter: rouge

paginate: 5
permalink: /:year/:month/:title

# Social share and comments.
enable-social-module: false
disqus-id: false # yourusername
twitter: false # yourusername
github: zoltanp
google: false # +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
